package main

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/qaustria/AutoPack-Go/packstore"
	"github.com/qaustria/AutoPack-Go/utils"
)

func main() {
	if err := run(); err != nil {
		if errors.Is(err, errSelectionCanceled) {
			fmt.Println("No texture pack selected.")
			return
		}
		fmt.Fprintln(os.Stderr, "Cone:", err)
		os.Exit(1)
	}
}

func run() error {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	args := os.Args[1:]
	if len(args) == 1 && (args[0] == "web" || args[0] == "--web") {
		return runWeb(ctx)
	}
	if len(args) >= 1 && args[0] == "batch" {
		return runBatch(ctx, args[1:])
	}
	return runCLI(ctx, args)
}

func newDefaultProcessor() (*Processor, error) {
	credentials, err := loadRobloxCredentials()
	if err != nil {
		return nil, err
	}
	return newProcessorForCredentials(credentials)
}

func newProcessorForCredentials(credentials robloxCredentials) (*Processor, error) {
	uploader, err := utils.NewAssetUploader(utils.UploaderConfig{
		APIKey: credentials.APIKey,
		Creator: utils.AssetCreator{
			UserID:  credentials.UserID,
			GroupID: credentials.GroupID,
		},
		Description: "Generated by Cone",
		// The JSON is designed for loaders running in games that may not be
		// owned by the uploader. Restricted meshes/textures are rejected there.
		// Roblox makes this setting irreversible for each created asset.
		AssetPrivacy:  utils.AssetPrivacyOpenUse,
		MaxConcurrent: uploadConcurrency(),
	})
	if err != nil {
		return nil, err
	}
	processor, err := NewProcessor(ProcessorConfig{Uploader: uploader})
	if err != nil {
		return nil, err
	}
	return processor, nil
}

func newWebRequestProcessor(ctx context.Context, apiKey, userID string) (uploadProcessor, error) {
	apiKey = strings.TrimSpace(apiKey)
	userID = strings.TrimSpace(userID)
	if apiKey == "" {
		return nil, errors.New("Roblox API key is required")
	}
	if userID == "" || strings.Trim(userID, "0123456789") != "" || strings.TrimLeft(userID, "0") == "" {
		return nil, errors.New("Roblox user ID must be a positive number")
	}
	processor, err := newProcessorForCredentials(robloxCredentials{APIKey: apiKey, UserID: userID})
	if err != nil {
		return nil, err
	}
	if err := processor.Validate(ctx); err != nil {
		return nil, err
	}
	return processor, nil
}

func runCLI(ctx context.Context, args []string) error {
	zipPath, err := selectedTexturePack(args)
	if err != nil {
		return err
	}
	processor, err := newDefaultProcessor()
	if err != nil {
		return err
	}
	if err := processor.Validate(ctx); err != nil {
		return err
	}
	started := time.Now()
	outputPath := availableOutputPath(zipPath)
	fmt.Println("Texture pack:", zipPath)
	fmt.Println("Porting...")
	result, err := processor.ProcessPath(ctx, zipPath, func(event ProgressEvent) {
		switch event.Stage {
		case ProgressPreparing, ProgressReceiving:
			if event.Message != "" {
				fmt.Println(event.Message)
			}
		case ProgressUploading:
			if event.Error != "" {
				fmt.Printf("[%d/%d] SKIPPED %s (using default): %s\n", event.Completed, event.Total, event.Name, event.Error)
				return
			}
			fmt.Printf("[%d/%d] %s\n", event.Completed, event.Total, event.Message)
		}
	})
	if err != nil {
		return err
	}
	if err := writeExportJSON(outputPath, result); err != nil {
		return err
	}
	fmt.Printf("Finished in %s\n", time.Since(started).Round(time.Millisecond))
	fmt.Println("JSON:", outputPath)
	return nil
}

func runWeb(ctx context.Context) error {
	webhookURL, err := loadDiscordWebhookURL()
	if err != nil {
		return err
	}
	var notifier PortNotifier
	if webhookURL != "" {
		notifier, err = NewDiscordNotifier(webhookURL)
		if err != nil {
			return err
		}
	}
	databasePath := strings.TrimSpace(os.Getenv("CONE_DATABASE_PATH"))
	if databasePath == "" {
		databasePath = filepath.Join("data", "cone.db")
	}
	store, err := packstore.Open(databasePath)
	if err != nil {
		return err
	}
	defer store.Close()
	maxConcurrentPorts, err := configuredMaxConcurrentPorts()
	if err != nil {
		return err
	}
	handler, err := NewCredentialWebHandlerWithOptions(newWebRequestProcessor, WebHandlerOptions{
		Notifier: notifier, Store: store, MaxConcurrentPorts: maxConcurrentPorts,
		BatchToken: strings.TrimSpace(os.Getenv("CONE_BATCH_TOKEN")),
	})
	if err != nil {
		return err
	}
	address := strings.TrimSpace(os.Getenv("AUTOPACK_ADDR"))
	if address == "" {
		address = "127.0.0.1:8080"
	}
	server := &http.Server{
		Addr:              address,
		Handler:           handler,
		ReadHeaderTimeout: 10 * time.Second,
		IdleTimeout:       2 * time.Minute,
	}
	result := make(chan error, 1)
	go func() {
		result <- server.ListenAndServe()
	}()
	fmt.Printf("Cone web interface: http://%s\n", address)
	if notifier == nil {
		fmt.Println("Discord notifications: disabled (set CONE_DISCORD_WEBHOOK_URL or DiscordWebhookURL in .env.go)")
	} else {
		fmt.Println("Discord notifications: enabled")
	}
	fmt.Println("Port history database:", store.Path())
	fmt.Println("Maximum simultaneous ports:", maxConcurrentPorts)
	fmt.Println("Press Ctrl+C to stop.")
	select {
	case err := <-result:
		if errors.Is(err, http.ErrServerClosed) {
			return nil
		}
		return err
	case <-ctx.Done():
		shutdownContext, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if err := server.Shutdown(shutdownContext); err != nil {
			return fmt.Errorf("shut down web server: %w", err)
		}
		return nil
	}
}

func configuredMaxConcurrentPorts() (int, error) {
	value := strings.TrimSpace(os.Getenv("CONE_MAX_CONCURRENT_PORTS"))
	if value == "" {
		return defaultMaxConcurrentPorts, nil
	}
	maximum, err := strconv.Atoi(value)
	if err != nil || maximum < 1 || maximum > 32 {
		return 0, errors.New("CONE_MAX_CONCURRENT_PORTS must be an integer from 1 to 32")
	}
	return maximum, nil
}

func selectedTexturePack(args []string) (string, error) {
	if len(args) > 1 {
		return "", errors.New("expected at most one texture-pack ZIP path")
	}
	if len(args) == 1 {
		return validateTexturePackPath(args[0])
	}
	path, err := SelectTexturePackZIP()
	if err != nil {
		return "", err
	}
	return validateTexturePackPath(path)
}

func validateTexturePackPath(path string) (string, error) {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("resolve texture-pack path: %w", err)
	}
	info, err := os.Stat(absolute)
	if err != nil {
		return "", fmt.Errorf("inspect texture pack %q: %w", absolute, err)
	}
	if !info.Mode().IsRegular() {
		return "", fmt.Errorf("texture pack %q is not a regular ZIP file", absolute)
	}
	if filepath.Ext(absolute) != ".zip" && filepath.Ext(absolute) != ".ZIP" {
		return "", fmt.Errorf("texture pack %q does not have a .zip extension", absolute)
	}
	return absolute, nil
}
